dist: xenial
sudo: required
language: java

env:
  global:
  - SONATYPE_USERNAME=ph@phloc.com
  - secure: "e/eBWwd/4QsvffFplovc7JFRWTIIczao3YIERwAAo2/IbLuWS/uCkorV0HW0WvF/1gBWl/Wsd6Zadmn+EgG0K7p4cnAsKmCXoS5Z+AaeYGM+/9i78N94MsiOJbWrx9L
AVOjH0IWay11JY+RnjSvSMMiVvdR2E6TVBVe2Ji5JIsoIizormxM1you2zlFpFfEJqKxspDcuSOuzTlyYsVDzEb0cYiGGogN/O6859HTjXWi54q6aaDh8x1It5TNpxXS06YW+DmW91
Nl6WDYotXuIbvvEv9Hhu5namD98TB1MzWCYjK/mpGV5uw5RHecp5By95ySQR6fwetRfA3u7br8torWL/O0UCO8HOnJyMGqlvJiXajBoxVA7W/stVnTaZpoqlMMuXvdZQPWWfN4nmma
+xDJd0VRm75FOLsTFT8FuuLtyAg1TFMFqlX2BBjsn+wIYVC1/Ni6aaTd51w0z/kNDjqjqZ8VNYcJb1Ebjz0QzZeMeLtR+TED5Yh3c+TYV6+ij/lx11Vak4CG97KtDEe4jWHp/76Onp
iigW1aCLqV2C3tNKLoFGSgwJqSGFQsxq5N4+Sw+U+vd+3zWhGswBTuAEdrb9bkxcfWzzPz9hlmuIGWConJP/9UnttefmRGHXWn9AEcyj3xeND8hSfw7kzS1Wo50NGvlm8/dq8YRZGe
xoN8="

addons:
  sonarcloud:
    organization: toop4eu
    token:
      secure: "opxeduVELfRmE6Q12ACpEwFv2SLX1vS/b+3yoXLluSz7M73E+KupGHcls327WTT73luuCuNjjX/hlqwd9myIbvFYNWcEla+TnKwZ6Fu5nsjkiqieCFABeITOSsXjC4c
2B+RsFjcSEihzdVAMW1LGiDm/82vY7B97XJqdr7mLfo1+gtmUXVaBgyeAgLzdHzosiCDaBd7qMzCWLcOch7kCJTehDdtwllYaljYx0RkKebW7Pz3AW4rB5Tbsi8vUdAsB3CjXoWTO+
0VitzjSX1dbX4C0AP+jAQeBacuox+F/GFr3RbeWczG6k/R5Fjb82RArqoMFfu/DAOyVLj3UeOL/UruOK0J0vyYVPOQQ0gWqk84UkNSI83ApTIngBhqG9YwN5KvVy8flcQKmJ5tmGXm
xuTK9k8ajKVTkT5WMOqiXzI1cpwGy36KHjGAcspeAY6GSK91qVchoK1BGLGwyAuJ9tWuta8zKM0qLW8uWUsm5VCEPFd/3kfnJkgwqEVRJYvoplvqYGUKQewjsVfhqtJ2GwJzhPaBBN
WWZPzxxuE5m6NXqGyk7M99se0VQO/bFnDyjHraCfkUGnW6lDpY/FU1f0BhWWI5NlhNgZkLMpN8nybtxr1vprr0jYrHEyHxZj5NTdjmfmDILSs+XSLC3CTshBjZT9E7yirUY/7mDy38
n62I="

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U

cache:
  directories:
  - "$HOME/.m2"

branches:
  only:
  - master

jobs:
  include:
  - stage: test
    jdk: openjdk8
    script:
    - mvn test -B -P coverage sonar:sonar
    after_success:
    - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
    - bash <(curl -s https://codecov.io/bash)
  - stage: test
    jdk: openjdk11
    script:
    - mvn test -B
  - stage: test
    jdk: openjdk14
    script:
    - mvn test -B
